name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches to avoid shallow clone issues

    # Step 2: Set up Python for Django (Backend)
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Set up Node.js for Next.js (Frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 4: Set up Node.js for Next.js (Frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
  # Step 5: Install Django backend dependencies
    - name: Install backend dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r portfolio_backend/requirements.txt

    # Step 6: Run Django backend tests (if applicable)
    - name: Run backend tests
      run: |
        source env/bin/activate
        python portfolio_backend/manage.py test

    # Step 7: Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    # Step 8: Build the frontend
    - name: Build frontend
      run: |
        cd frontend
        npm run build

    # Step 9: Deploy frontend to Vercel
    - name: Vercel Deployment Info
      run: echo "Frontend is deployed automatically via Vercel GitHub integration."

    # Step 10: Deploy Django backend to Heroku
    - name: Deploy to Heroku
      run: |
        git fetch --unshallow || git fetch --all --unshallow
        git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/shaniya.git HEAD:main